### Generate Token for testing

POST localhost:8080/token/generate
Accept: application/json

> {% client.global.set("auth_token", response.body.token); %}

### Validate Authorization

GET localhost:8080/token/validate
Authorization: Bearer {{auth_token}}


### call something through middleware
GET localhost:8080/profile
Authorization: Bearer {{auth_token}}
Accept: application/json
