### xyz-hub target is on http://192.168.188.117:8080

POST http://localhost:8080/token
Content-Type: application/json

{
  "username": "example",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Get service info

GET http://localhost:8080/proxy/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get OpenAPI description

GET http://192.168.188.117:8080/hub/static/openapi/stable.yaml

### get it through proxy

GET http://localhost:8080/proxy/hub/static/openapi/stable.yaml
Origin: http://localhost:8585


###
POST http://localhost:8080/token
Content-Type: application/json

{
  "username": "user",
  "password": "secret"
}