### login option with JSON structure that works by default

POST http://localhost:8080/token
Content-Type: application/json

{
  "username": "example",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### login option with JSON structure that works if users.txt is loaded (user/hello, admin/admin123)

POST http://localhost:8080/token
Content-Type: application/json

{
  "username": "user",
  "password": "hello"
}

> {% client.global.set("auth_token", response.body.token); %}


### login via form

POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username = example &
password = password &
redirect = success.html

### get proxy result through middleare
GET localhost:8080/proxy/
Authorization: Bearer {{auth_token}}
Content-Encoding: identity
